# Generated by Django 5.2.1 on 2025-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='attended',
        ),
        migrations.AddField(
            model_name='event',
            name='event_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('PARTICIPANT', 'Participant'), ('VOLUNTEER', 'Volunteer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EVENT_INVITE_PARTICIPANT', 'Event Invitation (Participant)'), ('EVENT_INVITE_VOLUNTEER', 'Event Invitation (Volunteer)'), ('EVENT_INVITE_MANAGER', 'Event Invitation (Manager)'), ('JOIN_REQUEST_MANAGER', 'Join Request (Manager)'), ('JOIN_REQUEST_PARTICIPANT', 'Join Request (Participant)'), ('JOIN_REQUEST_VOLUNTEER', 'Join Request (Volunteer)'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('INVITE_ACCEPTED', 'Invitation Accepted'), ('INVITE_DECLINED', 'Invitation Declined'), ('MANAGER_INVITE_ACCEPTED', 'Manager Invitation Accepted'), ('MANAGER_INVITE_DECLINED', 'Manager Invitation Declined'), ('EVENT_UPDATE', 'Event Details Updated'), ('ROLE_ASSIGNED', 'New Role Assigned')], max_length=50),
        ),
    ]
