# Generated by Django 5.2.1 on 2025-06-11 15:54

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_event_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=tasks.models.get_default_profile_picture, null=True, upload_to=tasks.models.user_profile_image_path),
        ),
    ]
